# Generated by Django 4.2.4 on 2023-08-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem_99', '0002_veiculo_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='Foto',
            new_name='capa',
        ),
    ]
