# Generated by Django 4.1.7 on 2023-03-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem_99', '0003_acessorio_cor_veiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acessorio',
            new_name='Acessório',
        ),
        migrations.RenameModel(
            old_name='Cor',
            new_name='Core',
        ),
        migrations.RenameModel(
            old_name='Veiculo',
            new_name='Veículo',
        ),
    ]
