# Generated by Django 4.2.4 on 2023-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('Garagem_99', '0004_rename_cessorio_veiculo_acessorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='capa',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capa',
            field=models.ManyToManyField(related_name='+', to='uploader.image'),
        ),
    ]
