# Generated by Django 4.1.7 on 2023-05-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem_99', '0004_rename_acessorio_acessório_rename_cor_core_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Core',
            new_name='Cor',
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
