# Generated by Django 4.1.7 on 2023-05-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem_99', '0005_rename_core_cor_alter_cor_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessório',
            new_name='Acessorio',
        ),
        migrations.RenameModel(
            old_name='Veículo',
            new_name='Veiculo',
        ),
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
