# Generated by Django 4.2.4 on 2023-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem_99', '0005_remove_veiculo_capa_veiculo_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
