# Generated by Django 4.2.4 on 2023-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem_99', '0006_veiculo_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorio',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='+', to='Garagem_99.acessorio'),
        ),
    ]
